name: Deploy to Google Composer

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: 'latest'

    - name: Authenticate to Google Cloud\
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: netskope
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}

    - name: Copy DAGs to Composer
      run: |
        gcloud composer environments storage dags import \
          --environment airflow-tutorial \
          --location us-central1 \
          --source dags

