name: Deploy to Google Composer

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: 'latest'

    - name: Decode GCP_SA_KEY_BASE64 and write to file
      run: echo -n "${{ secrets.GCP_SA_KEY }}" | base64 > key.json

    - name: Authenticate to Google Cloud
      run: gcloud auth activate-service-account ${{ secrets.GCP_SA_EMAIL }} --key-file=key.json

    - name: Copy DAGs to Composer
      run: |
        gcloud composer environments storage dags import \
          --environment netskope \
          --location us-central1 \
          --source dags

