name: Test Github Actions

on:
  push:
    branches:
      - main

env:
  GCP_INSTANCE: instance-20240812-082629
  ZONE: us-central1-c

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Remove Old DAGs
      run: |
        gcloud compute ssh ${{ env.GCP_INSTANCE }} --zone ${{ env.ZONE }} --command "rm -rf /tmp/dags"
        
    - name: Upload DAGs
      run: |
        gcloud compute scp --recurse dags ${{ env.GCP_INSTANCE }}:/tmp --zone ${{ env.ZONE }}

    - name: Move to OPT
      run: |
        gcloud compute ssh ${{ env.GCP_INSTANCE }} --zone ${{ env.ZONE }} --command "sudo mv --force /tmp/dags /opt/airflow/dags"    
