name: Test Github Actions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Remove Old DAGs
      run: |
        gcloud compute ssh instance-20240812-082629 --zone us-central1-c --command "rm -rf /tmp/dags"
        
    - name: Upload DAGs
      run: |
        gcloud compute scp --recurse dags instance-20240812-082629:/tmp --zone us-central1-c

    - name: Move to OPT
      run: |
        gcloud compute ssh instance-20240812-082629 --zone us-central1-c --command "sudo mv /tmp/dags /opt/"
      
